// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SIPIweb.Models;

namespace SIPIweb.Migrations
{
    [DbContext(typeof(SIPIContext))]
    partial class SIPIContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("SIPIweb.Models.informacion", b =>
                {
                    b.Property<long>("id_informacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<long>("id_usuario")
                        .HasColumnType("bigint");

                    b.Property<string>("informacion_cuerpo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("informacion_fechaLimite")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("informacion_fechaPublicacion")
                        .HasColumnType("datetime");

                    b.Property<string>("informacion_titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("id_informacion");

                    b.HasIndex("id_usuario");

                    b.ToTable("informacion");
                });

            modelBuilder.Entity("SIPIweb.Models.usuario", b =>
                {
                    b.Property<long>("id_usuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<DateTime>("usuario_birthday")
                        .HasColumnType("date");

                    b.Property<DateTime>("usuario_createdday")
                        .HasColumnType("date");

                    b.Property<string>("usuario_email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("usuario_login")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("usuario_pass")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int?>("usuario_tipo")
                        .HasColumnType("int");

                    b.HasKey("id_usuario");

                    b.ToTable("usuario");
                });

            modelBuilder.Entity("SIPIweb.Models.informacion", b =>
                {
                    b.HasOne("SIPIweb.Models.usuario", "id_usuarioNavigation")
                        .WithMany("informacions")
                        .HasForeignKey("id_usuario")
                        .HasConstraintName("FK_informacion_usuario")
                        .IsRequired();

                    b.Navigation("id_usuarioNavigation");
                });

            modelBuilder.Entity("SIPIweb.Models.usuario", b =>
                {
                    b.Navigation("informacions");
                });
#pragma warning restore 612, 618
        }
    }
}
